# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "bundle-app"
client_id = "ba773d8b48b08f3b37f6ab81cd86e1b9"
application_url = "https://kg-trains-rage-still.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,write_cart_transforms,read_products,read_cart_transforms"

[auth]
redirect_urls = [
  "https://kg-trains-rage-still.trycloudflare.com/auth/callback",
  "https://kg-trains-rage-still.trycloudflare.com/auth/shopify/callback",
  "https://kg-trains-rage-still.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-07"

[pos]
embedded = false
