# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "bundles-cart-transform"
client_id = "36f07ac7e23ac3ab2f23aec7ec108295"
application_url = "https://b910-2405-201-6007-5ca3-36e7-68b1-516c-97e4.ngrok-free.app"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,write_cart_transforms,read_products,read_cart_transforms"
use_legacy_install_flow = true

[auth]
redirect_urls = [
  "https://b910-2405-201-6007-5ca3-36e7-68b1-516c-97e4.ngrok-free.app/auth/callback",
  "https://b910-2405-201-6007-5ca3-36e7-68b1-516c-97e4.ngrok-free.app/auth/shopify/callback",
  "https://b910-2405-201-6007-5ca3-36e7-68b1-516c-97e4.ngrok-free.app/api/auth/callback"
]

[webhooks]
api_version = "2023-07"

[pos]
embedded = false
